#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#pagina_inicial:
#  path: /hello
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#  defaults:
#    template: 'hello_page.html.twig'